### ISSUE TITLE
Add CSS line wrapping to <pre> elements in default CSS

### ISSUE THREAD

**Issue by calebjones** [FroMage/jax-doclets#14]
REST API calls that have several query string parameters cause the "Example HTML" section to horizontally stretch unbounded.

For a drop-in &lt;pre&gt; CSS class which can be used, see: http://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag

Perhaps limiting the scope of the style to &lt;pre&gt; elements only inside the example section (via CSS selectors) so it doesn't conflict with other &lt;pre&gt; tags might be wise. But then again, generic wrapping behavior described in stackoverflow link is pretty universally desirable.

**Comment by FroMage** [comment]
Thanks good idea :)

**Comment by FroMage** [comment]
Fixed now, thanks.
