### ISSUE TITLE
JSON examples should have property names double quoted

### ISSUE THREAD

**Issue by stanio** [FroMage/jax-doclets#22]
Per <a href="http://json.org/">JSON specification</a> the property names should be double quoted, otherwise it is invalid JSON syntax.  The generated examples are not fully JSON "compatible" but they could be made a bit more useful by making the property name output compliant, anyway.

Proposed patch:

<pre>
diff --git a/doclets/src/main/java/com/lunatech/doclets/jax/jaxb/writers/JAXBClassWriter.java b/doclets/src/main/java/com/lunatech/doclets/jax/jaxb/writers/JAXBClassWriter.java
--- a/doclets/src/main/java/com/lunatech/doclets/jax/jaxb/writers/JAXBClassWriter.java
+++ b/doclets/src/main/java/com/lunatech/doclets/jax/jaxb/writers/JAXBClassWriter.java
@@ -249,25 +249,25 @@

   private void printJSONExample() {
     around("b", "JSON Example:");
     open("pre");
     if(((JAXBConfiguration)configuration).enableJSONTypeName)
-      print("{'" + jaxbClass.getName() + "':\n");
+      print("{\"" + jaxbClass.getName() + "\":\n");
     print(" {\n");
     Collection&lt;Attribute> attributes = jaxbClass.getAttributes();
     for (Attribute attribute : attributes) {
-      print("  '@");
+      print("  \"@");
       around("a href='#m_" + attribute.getName() + "'", attribute.getName());
-      print("': ");
+      print("\": ");
       printJSONMemberType(attribute, false);
       print(",\n");
     }
     Collection&lt;Element> elements = jaxbClass.getElements();
     for (Element element : elements) {
-      print("   '");
+      print("   \"");
       around("a href='#m_" + element.getName() + "'", element.isWrapped() ? element.getWrapperName() : element.getName());
-      print("': ");
+      print("\": ");
       printJSONMemberType(element, true);
       print(",\n");
     }
     for (Value value : jaxbClass.getValues()) {
       print("   ");</pre>

**Comment by FroMage** [comment]
Fixed now

**Comment by FroMage** [comment]
Thanks!
