### ISSUE TITLE
Provide switch to omit @ in JSON mapped XML attributes

### ISSUE THREAD

**Issue by stanio** [FroMage/jax-doclets#23]
Jackson supports mapping Java Beans to/from JSON using JAXB annotations:

http://wiki.fasterxml.com/JacksonJAXBAnnotations

Its mapping is really simple and doesn't try to distinguish XML features like attributes (vs. elements) and namespaces, so both of the following two versions:

<pre>
public class Foo {

    @XmlElement 
    public String bar;

    @XmlElement 
    public String baz;

}
</pre>

and:

<pre>
public class Foo {

    @XmlAttribute
    public String bar;

    @XmlElement 
    public String baz;

}
</pre>

get serialized as:

<pre>
{
    "bar" : "...",
    "baz" : "..."
}
</pre>

and not as:

<pre>
{
    "@bar" : "...",
    "baz" : "..."
}
</pre>

It would be nice if there's an option to omit the <code>@</code> in attribute names in the generated JSON examples, e.g. <code>-useplainjsonattributenames</code>, though this is a bit lengthy one.

**Comment by FroMage** [comment]
Good idea.

**Comment by anikitin** [comment]
Need this change as well.

**Comment by ilyavolk** [comment]
but, is there any case, in which <pre>@</pre> is needed in attribute name in JSON example ?
probably, it would be enough to remove <pre>@</pre> printing in JSON example.
patch JAXBClassWriter.printJSONExample 
was:

<pre>
      print("  \"@");
</pre>

become:

<pre>
      print("  \"");
</pre>

**Comment by FroMage** [comment]
It depends on your JSON marshaller. In RESTEasy the default is to get `@`.

**Comment by ilyavolk** [comment]
ok.
I'm not sure if the fix is enough.
1. JAXBDoclet.optionLength
   was:
   <pre>
   if ("-disablejaxbmethodoutput".equals(option)
       || "-disablejsontypename".equals(option)
       || "-disablexmlexample".equals(option)
       || "-disablejsonexample".equals(option)
     return 1;
   }
   </pre>

become

<pre>
    if ("-disablejaxbmethodoutput".equals(option)
        || "-disablejsontypename".equals(option)
        || "-disablexmlexample".equals(option)
        || "-disablejsonexample".equals(option)
        || "-useplainjsonattributenames".equals(option)) {
      return 1;
    }
</pre>


2.JAXBConfiguration
2.1. Add variable

<pre>public boolean useJSONPlainAttribute = false;</pre>

2.2. At the end of the function setOptions add code

<pre>useJSONPlainAttribute = Utils.hasOption(options, "-useplainjsonattributenames");</pre>


3.JAXBClassWriter.printJSONExample in the loop by attributes
was:

<pre>print("  \"@");</pre>

become:

<pre>
      print("   \"");
      if(!((JAXBConfiguration) configuration).useJSONPlainAttribute)
          print("@");
</pre>

**Comment by stanio** [comment]
Just for information, the requested behavior matches what's called _Natural_ JSON notation:

http://jersey.java.net/nonav/documentation/latest/json.html#d4e1058

There appear also _Mapped_, _Jettison-mapped_ and _Badgerfish_ notations:

http://jersey.java.net/nonav/documentation/latest/json.html#d4e949

These could be used like `-jsonnotaton natural` in future to switch between whole different behavior, if implemented.

**Comment by FroMage** [comment]
Done with `-jsonconvention mapped` in latest git.
