### ISSUE TITLE
Build fails because of a curved single quote

### ISSUE THREAD

**Issue by brendanlong** [FroMage/jax-doclets#31]
I checked out the project and tried a "mvn install", and it failed like this:

...
[INFO] [docbkx:generate-html {execution: generate-html}]
[INFO] Executing tasks
[INFO] Executed tasks
[INFO] Processing index.xml
Error on line 626 column 43 of file:///Users/blong/workspace/jax-doclets/docs/target/wikbook/src/index.xml:
  Error reported by XML parser: Invalid byte 1 of 1-byte UTF-8 sequence.

A little research led me to docs/src/main/wikbook/en/en-US/running.wiki, which contains a curved single quote that apparently doesn't get translated right. Turning it into a normal single quote fixed the build for me (I'll add a pull request once I figure out how they work).

**Comment by FroMage** [comment]
Funny I thought someone else had committed a fix for this. Could be in a pull request waiting for docs…

**Comment by brendanlong** [comment]
Oops, I didn't notice it was a minor commit it one of the pull requests:

https://github.com/orionhealth/jax-doclets/commit/815dfea15b61e08d8b3c42495651caa9265620f3

Also didn't realize creating a pull request opens an issue. I'm still getting used to this.

**Comment by FroMage** [comment]
Fixed now, thanks!
