### ISSUE TITLE
attributes rendered in json with leading @

### ISSUE THREAD

**Issue by antonpiatek** [FroMage/jax-doclets#40]
I have just started playing with jax-doclets, and the output examples for the jaxb output are coming out with values which would be xml attributes with a leading @ in the name.
e.g. XML
<application
 isRunEnabled="xsd:boolean" ....

JSON:
{'application':
 {
  '@isRunEnabled': Boolean, ....

My runtime engine (wink+jackson+jaxb on tomcat) does not render the json fields in this way (which is annoying but so be it). Is there any option or flag I can set to not describe the json fields in this way? My only other alternative is to hide the json examples, but I would quite like to show them.

**Comment by FroMage** [comment]
I think we've one patch due with an option for that.

**Comment by FroMage** [comment]
Done with `-jsonconvention mapped` in latest git.
