### ISSUE TITLE
java.util.Collection not recognized as collection

### ISSUE THREAD

**Issue by mwinkels** [FroMage/jax-doclets#42]
A bean with a property of type java.util.Collection is not recognized as a collection.

**Comment by mwinkels** [comment]
This is a patch for this issue:

From 81cb708d2af5164c7faf4c55d7e4fae81f7a7d68 Mon Sep 17 00:00:00 2001
From: Maarten Winkels maarten.winkels@ing.nl
Date: Fri, 13 Jul 2012 14:49:10 +0200
Subject: [PATCH] Fix for issue #42: recognize java.util.Collection as
 Collection.

---

 .../main/java/com/lunatech/doclets/jax/Utils.java  |    2 ++
 .../doclets/jax/jaxb/testcase/ClassExample.java    |   11 +++++++++++
 2 files changed, 13 insertions(+), 0 deletions(-)

diff --git a/doclets/src/main/java/com/lunatech/doclets/jax/Utils.java b/doclets/src/main/java/com/lunatech/doclets/jax/Utils.java
index 7ba58ab..61f38a8 100644
--- a/doclets/src/main/java/com/lunatech/doclets/jax/Utils.java
+++ b/doclets/src/main/java/com/lunatech/doclets/jax/Utils.java
@@ -232,6 +232,8 @@ public class Utils {
     ClassDoc doc = type.asClassDoc();
     if (doc == null)
       return null;
-    if (doc.qualifiedTypeName().equals(typeName))
-      return type;
   if (doc.isInterface())
     return findSuperTypeFromInterface(doc, typeName);
   if (doc.isClass() && !doc.isEnum() && !doc.isError() && !doc.isException())
  diff --git a/doclets/src/test/java/com/lunatech/doclets/jax/jaxb/testcase/ClassExample.java b/doclets/src/test/java/com/lunatech/doclets/jax/jaxb/testcase/ClassExample.java
  index 7e656f0..4d6f63d 100644
  --- a/doclets/src/test/java/com/lunatech/doclets/jax/jaxb/testcase/ClassExample.java
  +++ b/doclets/src/test/java/com/lunatech/doclets/jax/jaxb/testcase/ClassExample.java
  @@ -1,5 +1,6 @@
  package com.lunatech.doclets.jax.jaxb.testcase;

+import java.util.Collection;
 import java.util.Date;
 import java.util.List;

@@ -78,4 +79,14 @@ public class ClassExample {
     this.integerList = integerList;
   }
-  @XmlElement
-  private Collection<String> stringCollection;
-  
-  public Collection<String> getStringCollection() {
-    return stringCollection;
-  }
-  
-  public void setStringCollection(Collection<String> stringCollection) {
-    this.stringCollection = stringCollection;
-  }
  }
  -- 
  1.7.8.msysgit.0

**Comment by FroMage** [comment]
Thanks. Could you do a pull request for this please?

**Comment by FroMage** [comment]
Sorry you already did, thanks a lot :)
