### ISSUE TITLE
Release 0.10.1

### ISSUE THREAD

**Issue by wikier** [FroMage/jax-doclets#63]

**Comment by wikier** [comment]
moved all current open issue to new milestone: OK, I moved all the current open issues to 0.10.2: https://github.com/FroMage/jax-doclets/issues?milestone=5&page=1&state=open

**Comment by wikier** [comment]
artifacts released at sonatype: https://oss.sonatype.org/content/repositories/releases/com/lunatech/jax-doclets/doclets/0.10.1/

now it's just a matter of time until they sync into maven central

**Comment by FroMage** [comment]
Great! Many thanks!

**Comment by wikier** [comment]
already synced http://search.maven.org/#artifactdetails%7Ccom.lunatech.jax-doclets%7Cparent%7C0.10.1%7Cpom
